version: '3.7'

services:
  prometheus:
    image: 0fbb3f252560ca2693d507d690da15a1fc3209e158ee2381b513190a4e54d1fe
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
  
  grafana:
    image: b7915a5be6d2fa709592ef8f69af34778345e7af6e879259fb718801106d7169
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"

volumes:
  grafana-storage:
